// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SomeFunctionOKCode is the HTTP code returned for type SomeFunctionOK
const SomeFunctionOKCode int = 200

/*SomeFunctionOK All OK

swagger:response someFunctionOK
*/
type SomeFunctionOK struct {
}

// NewSomeFunctionOK creates SomeFunctionOK with default headers values
func NewSomeFunctionOK() *SomeFunctionOK {
	return &SomeFunctionOK{}
}

// WriteResponse to the client
func (o *SomeFunctionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SomeFunctionInternalServerErrorCode is the HTTP code returned for type SomeFunctionInternalServerError
const SomeFunctionInternalServerErrorCode int = 500

/*SomeFunctionInternalServerError Some things are not okay.

swagger:response someFunctionInternalServerError
*/
type SomeFunctionInternalServerError struct {
}

// NewSomeFunctionInternalServerError creates SomeFunctionInternalServerError with default headers values
func NewSomeFunctionInternalServerError() *SomeFunctionInternalServerError {
	return &SomeFunctionInternalServerError{}
}

// WriteResponse to the client
func (o *SomeFunctionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
