swagger: "2.0"
info:
  title: Service1
  version: "1.0.0"
host: 127.0.0.1:8001
basePath: /service1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /somefunction:
    get:
      operationId: someFunction
      description: someFunction
      responses:
        200:
          description: All OK
        500:
          description: Some things are not okay.
definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string