// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SomeFunctionReader is a Reader for the SomeFunction structure.
type SomeFunctionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SomeFunctionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSomeFunctionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewSomeFunctionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSomeFunctionOK creates a SomeFunctionOK with default headers values
func NewSomeFunctionOK() *SomeFunctionOK {
	return &SomeFunctionOK{}
}

/*SomeFunctionOK handles this case with default header values.

All OK
*/
type SomeFunctionOK struct {
}

func (o *SomeFunctionOK) Error() string {
	return fmt.Sprintf("[GET /somefunction][%d] someFunctionOK ", 200)
}

func (o *SomeFunctionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSomeFunctionInternalServerError creates a SomeFunctionInternalServerError with default headers values
func NewSomeFunctionInternalServerError() *SomeFunctionInternalServerError {
	return &SomeFunctionInternalServerError{}
}

/*SomeFunctionInternalServerError handles this case with default header values.

Some things are not okay.
*/
type SomeFunctionInternalServerError struct {
}

func (o *SomeFunctionInternalServerError) Error() string {
	return fmt.Sprintf("[GET /somefunction][%d] someFunctionInternalServerError ", 500)
}

func (o *SomeFunctionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
