// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Service1

    Schemes:
      http
    Host: 127.0.0.1:8001
    BasePath: /service1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
